### ISSUE TITLE
The code of modified version of OpenAI baselines could not find

### ISSUE THREAD

**Issue by hnsyzjianghan** [eanswer/LearningToFly#1]
Hi Xu Jie , I am reading your papers and I want to congratulate you for the great work. It is really nice to see your drone being trained in simulation and then flying in a stable manner in a real-world scenario.
I have a question is that in the Training Section of the readme, you remind that the code relies on a modified version of OpenAI baselines in git@github.com:eanswer/openai_baselines.git.  However, I can not find this code,  could you give me a correct download link? or some suggestions to modify the source code.
Thanks in advance.

**Comment by eanswer** [comment]
Sorry for late reply. The repository should be public. could you try to access: https://github.com/eanswer/openai_baselines. Let me know if it works out for you.
